routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| facilities Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('/login', 'AuthController@viewLogin');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => ['auth:admin']], function () {

    Route::get('/', 'HomeController@index');

    Route::get('home', 'HomeController@index');

    Route::get('reset-password', 'AuthController@ResetPasswordView');
    Route::post('reset-password', 'AuthController@ResetPassword');

    Route::get('settings', 'SettingController@view');
    Route::post('settings', 'SettingController@update');

    Route::resource('developer/setting', 'DeveloperSetting');
    Route::resource('developer/settings/categories', 'SettingCategoryController');

    Route::resource('users', 'UserController');
    Route::get('users/activation/{id}', 'UserController@activation')->name('users.users_activation');

    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('regions', 'RegionController');

    Route::resource('posts', 'PostController');
    Route::get('posts/toggle-boolean/{id}/{action}', 'PostController@toggleBoolean')->name('admin.posts.toggleBoolean');

    Route::resource('emergencies', 'EmergencyController');
    Route::get('emergencies/toggle-boolean/{id}/{action}', 'EmergencyController@toggleBoolean')->name('admin.emergencies.toggleBoolean');

    Route::resource('pharmacies', 'PharmacyController');
    Route::get('pharmacies/toggle-boolean/{id}/{action}', 'PharmacyController@toggleBoolean')->name('admin.pharmacies.toggleBoolean');
});

Route::get('country/cities/{id}', 'CityController@getCity');
Route::get('city/regions/{id}', 'RegionController@getRegion');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function () {
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');

    return 'done';
});

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'FrontController@index')->name('index');
Route::get('about', 'FrontController@about')->name('about');
Route::get('contact', 'FrontController@contact')->name('contact');
Route::post('contact-us', 'FrontController@contactSubmit')->name('contact-us');
Route::get('job', 'FrontController@jobs')->name('jobs');
Route::get('job-apply/{id}', 'FrontController@jobApply');
Route::post('job-apply/{id}', 'FrontController@jobApplySubmit');
Route::get('partner-signup', 'FrontController@storeSignup');
Route::post('partner-signup', 'FrontController@storeSignupSubmit');
Route::get('terms', 'FrontController@terms')->name('terms');
Route::get('policies', 'FrontController@policies')->name('policy');

app/Http/Controllers/Facility/AmbulanceController.php
<?php

namespace App\Http\Controllers\Facility;

use App\Charts\AmbulanceAvailability;
use App\Http\Controllers\Controller;
use App\Models\Country;
use App\Models\Delivery as Ambulance;
use App\Models\Delivery;
use App\Models\HospitalUser;
use App\Models\Service;
use App\MyHelper\Helper;
use App\MyHelper\Photo;
use DB;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
use Response;
use Hash;
use Auth;
use Spatie\Permission\Models\Role;

class AmbulanceController extends Controller
{
    protected $model;
    protected $guard = 'facilities';
    protected $url = 'facilities/ambulances/';
    protected $viewsDomain = 'facilities.ambulances.';

    public function __construct()
    {
        $this->model = new Ambulance();
        $this->guard = 'facilities';
    }

    /**
     * @param $view
     * @param array $params
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    public function index(Request $request)
    {
        $facility = auth($this->guard)->user()->hospital;

        $records = $facility->ambulances()->where(function ($q) use ($request) {
            if ($request->name) {
                $q->where(function ($q) use ($request) {

                    $q->where('name', 'LIKE', '%' . $request->name . '%')
                        ->orWhere('email', 'LIKE', '%' . $request->name . '%');
                });
            }
            if ($request->role_name) {

                $q->whereHas('roles', function ($q) use ($request) {

                    $q->where('display_name', 'LIKE', '%' . $request->role_name . '%');
                });
            }

            if ($request->service_id) {

                $q->whereHas('services', function ($q) use ($request) {

                    $q->where('service_id', $request->service_id);
                });
            }

            if ($request->from) {
                $q->whereDate('created_at', '>=', Helper::convertDateTime($request->from));
            }

            if ($request->to) {
                $q->whereDate('created_at', '<=', Helper::convertDateTime($request->to));
            }


        })->latest()->paginate(20);
        return $this->view('index', compact('records'));
    }

    public function create(User $model)
    {
        $facility = auth($this->guard)->user()->hospital;
        $model = new HospitalUser();
        $roles = $facility->roles()->get();

        return $this->view('create', compact('model', 'roles'));
    }

    public function store(Request $request)
    {

        $facility = auth($this->guard)->user()->hospital;

        $rules =
            [
                'name' => 'required',
                'country' => 'required',
                'services' => 'required',
                'd_o_b' => 'required',
                'services.*' => 'exists:services,id',
                'car_type_id' => 'required|exists:car_types,id',
                'city' => 'required',
                'region_id' => 'required|exists:regions,id',
                'user_name' => 'required|unique:deliveries',
                'email' => 'required|email|unique:deliveries',
                'phone' => 'required|unique:deliveries',
                'car_number' => 'required|unique:deliveries',
                'nationality' => 'required',
                'photo' => 'required|image|mimes:jpeg,jpg,png,gif,svg',
                'transport_photo' => 'required|image|mimes:jpeg,jpg,png,gif,svg',
            ];

        $error_sms =
            [
                'name.required' => 'الرجاء ادخال الاسم ',
                'car_type_id.required' => 'الرجاء ادخال نوع السيارة ',
                'services.required' => 'الرجاء ادخال الخدمة ',
                'services.*.exists' => 'الرجاء ادخال الخدمة ',
                'email.unique' => ' البريد الالكتروني موجود بالفعل',
                'email.required' => 'الرجاء ادخال البريد الالكتروني',
                'email.email' => 'الرجاء ادخال البريد الالكتروني بطريقة صحيحة',
                'country.required' => 'المنطقة مطلوبة',
                'city.required' => 'الرجاء ادخال المدينة',
                'region_id.required' => 'الرجاء ادخال الحي',
                'user_name.required' => 'الرجاء ادخال إسم المستخدم ',
                'user_name.unique' => ' إسم المستخدم موجود بالفعل',
                'phone.required' => 'الرجاء ادخال رقم الهاتف',
                'car_number.required' => 'الرجاء ادخال رقم السيارة',
                'car_number.unique' => 'رقم السيارة موجود بالفعل',
                'nationality.required' => 'الرجاء ادخال الجنسية',
                'photo.required' => 'الرجاء ادخال صورة السائق',
                'photo.image' => 'الرجاء التأكد من إدخال صورة',
                'photo.mimes' => 'الرجاء التأكد من إدخال صورة',
                'transport_photo.required' => 'الرجاء ادخال صورة السيارة',
                'transport_photo.image' => 'الرجاء التأكد من إدخال صورة',
                'transport_photo.mimes' => 'الرجاء التأكد من إدخال صورة',

            ];

        $data = validator()->make($request->all(), $rules, $error_sms);

        if ($data->fails()) {

            return response()->json([
                'error' => true,
                'errors' => $data->errors(),
                'code' => 400
            ], 400);

        }
        $record = $facility->ambulances()->create($request->all());

        $record->update(['password' => Hash::make($request->password)]);

        $record->services()->attach($request->services);

        Photo::addOriginalPhoto($request->file('photo'), $record, 'deliveries', 'photos');
        Photo::addOriginalPhoto($request->file('transport_photo'), $record, 'transports', 'photos', 'transport');

        session()->flash('success', 'تم إرسال الطلب للإدارة بنجاح');
        return response()->json([
            'success' => true,
            'url' => url('/facilities/ambulances')
        ]);
    }


    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function stats(Request $request)
    {
        $facility = auth($this->guard)->user()->hospital;
        $countries = Country::pluck('name', 'id')->toArray();

        $services = Service::whereIn('type', ['care', 'event', 'provider', 'pharmacy'])

            ->withCount(['workingAmbulances' => function ($query) use ($request,$facility) {
                $query->where('hospital_id' , $facility->id);
            if ($request->country_id) {
                $query->whereHas('region', function ($query) use ($request) {
                    $query->whereHas('city', function ($query) use ($request) {
                        $query->where('country_id', $request->country_id);
                    });
                });
            }
        }])->where(function ($query) use ($request) {

        })->with('workingAmbulances')->get();

        $charts = [];

        foreach ($services as $service)
        {
            $chart = new AmbulanceAvailability();

            $open = $service->workingAmbulances()->where(function($query) use($request){
                if ($request->country_id)
                {
                    $query->whereHas('region',function ($query) use($request){
                        $query->whereHas('city',function ($query) use($request){
                            $query->where('country_id',$request->country_id);
                        });
                    });
                }
            })->get()->where('types','open')->count();

            $busy = $service->workingAmbulances()->where(function($query) use($request){
                if ($request->country_id)
                {
                    $query->whereHas('region',function ($query) use($request){
                        $query->whereHas('city',function ($query) use($request){
                            $query->where('country_id',$request->country_id);
                        });
                    });
                }
            })->get()->where('types','busy')->count();

            $closed = $service->workingAmbulances()->where(function($query) use($request){
                if ($request->country_id)
                {
                    $query->whereHas('region',function ($query) use($request){
                        $query->whereHas('city',function ($query) use($request){
                            $query->where('country_id',$request->country_id);
                        });
                    });
                }
            })->get()->where('types','closed')->count();

//            info($service->name.'['.$open.','.$busy.','.$closed.']');
            $chart->title($service->name)
                ->labels(['متاح', 'مشغول', 'مغلق'])
                ->dataset("الإسعاف",'pie',[$open,$busy,$closed])
                ->backgroundcolor(["rgb(76, 175, 80)","rgb(253, 221, 17)","rgb(175, 20, 20)"]);
            $charts[] = $chart;
        }

        return $this->view('stats', compact('countries', 'services', 'charts'));
    }

    public function show($id)
    {

        $facility = auth($this->guard)->user()->hospital;
        $record = $facility->ambulances()->findOrFail($id);

        $totalCount = $record->reviews()->count();
        $reviews = [
            "status" => 1,
            "massage" => "SUCCESS",
            'provider_rate' => number_format($record->rate, 1),
            'total_count_reviews' => $totalCount,
            'counts' => (new Helper())->ratePresent($record , $record->reviews->count())
        ];
        return $this->view('show', compact('record','reviews'));
    }

    public function edit($id)
    {

        $facility = auth($this->guard)->user()->hospital;
        $model = $facility->ambulances()->findOrFail($id);

        return $this->view('edit', compact('model'));
    }

    public function update(Request $request, $id)
    {

app/Http/Controllers/Facility/AuthController.php
<?php
namespace App\Http\Controllers\Facility;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{

    public function viewLogin()
    {
        return view('facilities.auth.login');
    }


    public function login(Request $request)
    {

        $rules = [
            'email' => 'required|email|exists:hospital_users,email',
            'password' => 'required'
        ];

        $error_sms =
            [
                'email.required'=>'البريد الإلكتروني خطأ ',
                'email.email'=>'الرجاء إدخال البريد الإلكتروني بالشكل الصحيح ',
                'email.exists'=>'البريد الإلكتروني خطأ ',
                'password.required'=>'الرجاء ادخال كلمة المرور ',

            ];

        $data = validator()->make($request->all(), $rules,$error_sms);

        if ($data->fails()) {

            return back()->withInput()->withErrors($data->errors());

        }else{

            $remember = $request->input('remember') && $request->remember == 1 ? $request->remember : 0;

            if(auth()->guard('facilities')->attempt(['email' => $request->email , 'password' => $request->password],$remember))
            {
                return redirect('facilities/home');
            }else{
                return back()->withInput()->withErrors(['password' => 'كلمة المرور غير صحيحة ']);
            }
        }

    }

    //reset password


    public function ResetPasswordView()
    {
        return view('facilities.reset_password.index');
    }

    public function ResetPassword(Request $request)
    {
        $rules =
            [

                'old_password' => 'required',
                'password' => 'required|confirmed|min:8',

            ];

        $error_sms =
            [
                'old_password.required'=>'الرجاء ادخال كلمة المرور الحالية ',
                'password.required'=>'الرجاء ادخال كلمة المرور الجديدة',
                'password.min'=>'الرجاء ادخال كلمة المرور الجديدة اكثر من ثمان حروف',
                'password.confirmed'=>'الرجاء التاكد من كلمة المرور الجديدة',

            ];

        $validator = validator()->make($request->all() , $rules , $error_sms);

        if ($validator->fails())
        {
            return back()->withInput()->withErrors($validator->errors());
        }

        if(Hash::check($request->old_password , auth('facilities')->user()->password))
        {
            auth('facilities')->user()->update(['password'=>Hash::make($request->password)]);


            session()->flash('success' , 'تمت تحديث بنجاح');
            return redirect('facilities/reset-password');

        }else{
            $errors = ['old_password' => 'الرجاء ادخال كلمة المرور الحالية '];
            return redirect('facilities/reset-password')->withInput()->withErrors($errors);
        }

    }

}

resources/views/facilities/ambulances/create.blade.php
@extends('facilities.layouts.main',[
                                'page_header'       => 'سيارات الإسعاف',
                                'page_description'  => 'اضافة سيارة',
                                'link' => url('facilities/ambulances')
                                ])


@section('content')
    <!-- general form elements -->
    <div class="ibox ibox-primary">
        <!-- form start -->
        {!! Form::model($model,[
                                'action'=>'Facility\AmbulanceController@store',
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'POST',
                                'files' => true
                                ])!!}

        <div class="ibox-content">

            @include('facilities.ambulances.form')

            <div class="ibox-footer">
                <button type="submit" class="btn btn-primary" id="myBtn">إرسال للإدارة</button>
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/facilities/ambulances/edit.blade.php
@extends('facilities.layouts.main',[
                                    'page_header'       => 'سيارات الأسعاف',
                                    'page_description'  => 'تعديل السيارة',
                                'link' => url('facilities/ambulances')
                                ])
@section('content')
    <!-- general form elements -->
    <div class="ibox ibox-primary">
        <!-- form start -->
        {!! Form::model($model,[
                                'url'=>url('facilities/ambulances/'.$model->id),
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'PUT',
                                'files' => true
                                ])!!}

        <div class="ibox-content">
            <div class="clearfix"></div>
            <br>
            @include('facilities.ambulances.form')

            <div class="ibox-footer">
                <button type="submit" class="btn btn-primary" id="myBtn">حفظ</button>
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/facilities/ambulances/form.blade.php
@inject(countries , App\Models\Country)
@inject(services , App\Models\Service)
@inject(car_types , App\Models\CarType)
@inject(cities , App\Models\City)
@inject(regions , App\Models\Region)

<div class="row">
    <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-6">
                {!! \App\MyHelper\Field::fileWithPreview('photo','صورة السائق') !!}
            </div>
            <div class="col-sm-6 text-left">
                @if($model->photo)
                    <div class="col-md-4">
                        <img src="{{url($model->photo)}}" alt="" class="img-responsive thumbnail">
                    </div>
                    <div class="clearfix"></div>
                @endif
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-6">
                {!! \App\MyHelper\Field::fileWithPreview('transport_photo','صورة السيارة') !!}
            </div>
            <div class="col-sm-6 text-left">
                @if($model->transport_photo)
                    <div class="col-md-4">
                        <img src="{{url($model->transport_photo)}}" alt="" class="img-responsive thumbnail">
                    </div>
                    <div class="clearfix"></div>
                @endif
            </div>
        </div>
    </div>
</div>

{!! \App\MyHelper\Field::multiSelect('services' , 'الخدمات' , $services->whereIn('type' , ['care','pharmacy','provider'])->pluck('name','id')->toArray())!!}
{!! \App\MyHelper\Field::select('car_type_id' , 'نوع السيارة' , $car_types->pluck('name','id')->toArray())!!}
{!! \App\MyHelper\Field::select('country' , 'منطقة' , $countries->pluck('name','id')->toArray() , $model->region ?optional($model->region->city->country)->id : null)!!}


{!! \App\MyHelper\Field::select(
'city' ,
 'مدينة' ,
 $model->region ?
 $cities->where('country_id' , optional($model->region->city->country)->id)->pluck('name','id')->toArray()
  :
  [] ,
  $model->region ?optional($model->region->city)->id : null
  )!!}

{!! \App\MyHelper\Field::select('region_id' , 'الحي' ,
$model->region ? $regions->where('city_id' , optional($model->region->city)->id)->pluck('name','id')->toArray() :  []
, $model->region ?optional($model->region)->id : null)!!}

{!! \App\MyHelper\Field::text('name' , 'الاسم')!!}
{!! \App\MyHelper\Field::text('user_name' , 'إسم دخول المستخدم')!!}
{!! \App\MyHelper\Field::email('email' , 'البريد الإلكتروني')!!}
{!! \App\MyHelper\Field::number('phone' , 'رقم الهاتف')!!}
{!! \App\MyHelper\Field::date('d_o_b' , 'تاريخ الميلاد' ,
null,
 \Carbon\Carbon::now()->subYears(3)->toDateString() ,
  \Carbon\Carbon::now()->subYears(200)->toDateString())
  !!}
{!! \App\MyHelper\Field::number('car_number' , 'رقم السيارة')!!}
{!! \App\MyHelper\Field::text('nationality' , 'جنسية السائق')!!}


@push('scripts')

    <script>
        $(document).ready(function () {

            $('#myForm').submit(function (e) {
                e.preventDefault();
                var url = $('#myForm').attr('action');
                var form_data = new FormData(this);


                $(".help-block").hide();
                $(".has-error").removeClass('has-error');

                $('#myBtn').attr('disabled', 'disabled');


                $.ajax({
                    url: url,
                    type: 'post',
                    data: form_data,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {

                        var url = data.url;

                        if (url) {

                            window.location = url;
                        }
                    },
                    error: function (data) {
                        var error = data.responseJSON.errors;

                        $('#myBtn').removeAttr('disabled');

                        $.each(error, function (key, value) {

                            $('#' + key + '_error').text('').append(value);
                            $('#' + key + '_error').parent().show();
                            $('#' + key + '_error').parent().parent().addClass('has-error');

                        });
                    }
                });
            });

            $('#country').change(function () {

                var url = '{!! url('admin/country/cities') !!}/' + $('#country').val();

                $.ajax({
                    url: url,
                    type: 'get',
                    success: function (data) {
                        console.log(data);
                        var option = '<option>' + 'إختر المدينة' + '</option>';
                        $.each(data.data, function (index, item) {
                            option += '<option value="' + item.id + '">' + item.name + '</option>';
                        });

                        $('#city').text('').append(option);
                    },
                    error: function (data) {
                        $('#city').text('').append('<option value="">لا يوجد مدن في هذه المنطقة</option>');
                    }
                });
            });

            $('#city').change(function () {

                var url = '{!! url('admin/city/regions') !!}/' + $('#city').val();

                $.ajax({
                    url: url,
                    type: 'get',
                    success: function (data) {
                        var option = '<option>' + 'إختر الحي' + '</option>';
                        $.each(data.data, function (index, item) {
                            option += '<option value="' + item.id + '">' + item.name + '</option>';
                        });

                        $('#region_id').text('').append(option);
                    },
                    error: function (data) {
                        $('#region_id').text('').append('<option value="">لا يوجد أحياء في هذه المنطقة</option>');
                    }
                });
            });
        });
    </script>
@endpush

resources/views/facilities/ambulances/get-ambulance.blade.php
@if(!$delivery)

    <div class="alert alert-danger">
        <p>تعذر الحصول على البيانات</p>
    </div>

@else

    <table class="table">
        <tr>
            <th>الحالة</th>
            <td>{!! $delivery->case_label !!}</td>
        </tr>
        <tr>
            <th>الاسم</th>
            <td>{{$delivery->name}}</td>
        </tr>
        <tr>
            <th>التليفون</th>
            <td>{{$delivery->phone}}</td>
        </tr>
        <tr>
            <th>المنطقة</th>
            <td>
                @if($delivery->region)
                    {{$delivery->region->name}}
                    @if($delivery->region->city)
                        - {{$delivery->region->city->name}}
                        @if($delivery->region->city->country)
                            - {{$delivery->region->city->country->name}}
                        @endif
                    @endif
                @endif
            </td>
        </tr>
        @if($delivery->latitude && $delivery->longitude)
            <tr>
                <th>اللوكيشن</th>
                <td>
                    <a href="{{url('http://maps.google.com/?q='.$delivery->latitude.','.$delivery->longitude)}}"
                       target="_blank" class="btn btn-danger">
                        <i class="fa fa-map-marker"></i>
                    </a>
                </td>
            </tr>
        @endif
    </table>

@endif

resources/views/facilities/ambulances/stats.blade.php
@extends('facilities.layouts.main',[
								'page_header'		=> 'سيارات الإسعاف',
								'page_description'	=> 'عرض السيارات',
                                'link' => url('facilities/ambulances')

								])
@section('content')
    @push('styles')
        {{-- ChartStyle --}}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
    @endpush
    <div class="ibox-content">
        <div class="box-body">
            <div class="box-header">
                <div class="row">
                    <div class="col-sm-3">
                        {!! Form::open([
                       'method' => 'get'
                       ]) !!}
                        <div class="form-group">
                            <label for="">اختر المنطقة</label>
                            {!! Form::select('country_id',$countries,request()->input('country_id'),[
                            'placeholder' => 'كل المناطق',
                            'class' => 'form-control',
                            'onchange' => 'submit()'
                            ]) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                    <div class="col-sm-9">
                        <ul class="nav nav-pills navbar-left">
                            @foreach($services as $service)
                                <li role="presentation" class="bg-gray" style="margin-bottom: 10px;min-width:200px;">
                                    <a href="{{url('facilities/ambulances?service_id='.$service->id.'&country='.request()->input('country_id'))}}">{{$service->name}}
                                        <span class="mr-3 badge badge-info">{{$service->working_ambulances_count}}</span></a>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <br>
                <div class="row">
                    @foreach($charts as $chart)
                        <div class="col-sm-4">
                            @push('scripts')
                                {!! $chart->script() !!}
                            @endpush
                            {{$chart->container()}}
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection