routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| facilities Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('/login', 'AuthController@viewLogin');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => ['auth:admin']], function () {

    Route::get('/', 'HomeController@index');

    Route::get('home', 'HomeController@index');

    Route::get('reset-password', 'AuthController@ResetPasswordView');
    Route::post('reset-password', 'AuthController@ResetPassword');

    Route::get('settings', 'SettingController@view');
    Route::post('settings', 'SettingController@update');

    Route::resource('developer/setting', 'DeveloperSetting');
    Route::resource('developer/settings/categories', 'SettingCategoryController');

    Route::resource('users', 'UserController');
    Route::get('users/activation/{id}', 'UserController@activation')->name('users.users_activation');

    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('regions', 'RegionController');

    Route::resource('posts', 'PostController');
    Route::get('posts/toggle-boolean/{id}/{action}', 'PostController@toggleBoolean')->name('admin.posts.toggleBoolean');

    Route::resource('emergencies', 'EmergencyController');
    Route::get('emergencies/toggle-boolean/{id}/{action}', 'EmergencyController@toggleBoolean')->name('admin.emergencies.toggleBoolean');

    Route::resource('pharmacies', 'PharmacyController');
    Route::get('pharmacies/toggle-boolean/{id}/{action}', 'PharmacyController@toggleBoolean')->name('admin.pharmacies.toggleBoolean');
});

Route::get('country/cities/{id}', 'CityController@getCity');
Route::get('city/regions/{id}', 'RegionController@getRegion');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function () {
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');

    return 'done';
});

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'FrontController@index')->name('index');
Route::get('about', 'FrontController@about')->name('about');
Route::get('contact', 'FrontController@contact')->name('contact');
Route::post('contact-us', 'FrontController@contactSubmit')->name('contact-us');
Route::get('job', 'FrontController@jobs')->name('jobs');
Route::get('job-apply/{id}', 'FrontController@jobApply');
Route::post('job-apply/{id}', 'FrontController@jobApplySubmit');
Route::get('partner-signup', 'FrontController@storeSignup');
Route::post('partner-signup', 'FrontController@storeSignupSubmit');
Route::get('terms', 'FrontController@terms')->name('terms');
Route::get('policies', 'FrontController@policies')->name('policy');

app/Http/Controllers/Admin/DeveloperSetting.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use App\my_helper\Helper;
use Illuminate\Http\Request;
use Response;

class DeveloperSetting extends Controller
{
    protected $model;
    protected $viewsDomain = 'admin.developer_setting.';

    public function __construct()
    {
        $this->model = new Setting();
    }
    /**
     * @param $view
     * @param array $params
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $records = Setting::latest()->paginate(20);

        return $this->view('index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = $this->model;
        $validation = null;
        return $this->view('create',compact('model' ,'validation'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules =
            [
                'settings_category_id'  => 'required|exists:settings_categories,id',
                'display_name'           => 'required',
                'key'           => 'required',
                'value'           => 'required',
                'data_type'           => 'required',
                'validation'           => 'required',
                'level'           => 'required',
            ];


        $data = validator()->make($request->all() , $rules  );

        if($data->fails())
        {
            return back()->withInput()->withErrors($data->errors());
        }

        $record = $this->model->create($request->all());


        $record->validation()->create(['value' => $request->validation]);


        session()->flash('success', 'تمت الاضافة بنجاح');
        return redirect('admin/developer/setting');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = $this->model->findOrFail($id);
        $validation = $model->validation ? $model->validation->value : null;

        return $this->view('edit',compact('model' , 'validation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules =
            [
                'settings_category_id'  => 'required|exists:settings_categories,id',
                'display_name'           => 'required',
                'key'           => 'required',
                'value'           => 'required',
                'data_type'           => 'required',
                'validation'           => 'required',
                'level'           => 'required',
            ];

        $data = validator()->make($request->all() , $rules  );

        if($data->fails())
        {
            return back()->withInput()->withErrors($data->errors());
        }

        $record = $this->model->findOrFail($id);

        $record->update($request->all());

        if($record->validation()->count())
        {
            $record->validation()->update(['value' => $request->validation]);
        }else{
            $record->validation()->create(['value' => $request->validation]);
        }


        session()->flash('success' , 'تمت تحديث بنجاح');
        return redirect('admin/developer/setting/'.$id.'/edit');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = $this->model->findOrFail($id);

        if($record->data_type == 'mulifileWithPreview' && $record->photos()->count())
        {
            Helper::deletePhoto($record,'photos','normal',true);

        }elseif ($record->data_type == 'fileWithPreview' && $record->photo)
        {
            Helper::deletePhoto($record);
        }

        $record->validation()->delete();
        $record->delete();
        $data = [
            'status' => 1,
            'msg' => 'تم الحذف بنجاح',
            'id' => $id
        ];
        return Response::json($data, 200);
    }


}

resources/views/admin/developer_setting/create.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'الاعدادات',
                                'page_description'  => 'اعدادات التطبيق',
                                 'link' => url('admin/developer/setting')
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'DeveloperSetting@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST',
                            'files' => true
                            ])!!}

    <div class="box-body">

        @include('admin.developer_setting.form')

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/developer_setting/edit.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'الاعدادات',
                                'page_description'  => 'اعدادات التطبيق',
                                 'link' => url('admin/developer/setting')
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'url'=>url('admin/developer/setting/'.$model->id),
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT',
                            'files' => true
                            ])!!}

    <div class="box-body">
        <div class="clearfix"></div>
        <br>
        @include('admin.developer_setting.form')

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/developer_setting/form.blade.php
@inject('categories' , App\Models\SettingsCategory)
{!! \App\MyHelper\Field::select('settings_category_id' , 'category', $categories->pluck('name','id')->toArray())!!}
{!! \App\MyHelper\Field::text('display_name' , 'label name ')!!}
{!! \App\MyHelper\Field::text('key' , 'field name') !!}
{!! \App\MyHelper\Field::text('value' , 'value') !!}
{!! \App\MyHelper\Field::text('validation' , 'validation' , $validation) !!}
{!!  \App\MyHelper\Field::select('data_type', 'data type' , [
   'fileWithPreview'=> 'fileWithPreview',
   'mulifileWithPreview'=> 'mulifileWithPreview',
   'editor'  => 'editor',
   'textarea'=> 'textarea',
   'number'  => 'number',
   'email'   => 'email',
   'date'    => 'date',
   'text'    => 'text'
] ) !!}

{!! \App\MyHelper\Field::number('level' , 'level')!!}

resources/views/admin/developer_setting/index.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'الاعدادات',
                                'page_description'  => 'اعدادات التطبيق',
                                 'link' => url('admin/developer/setting')
                                ])
@section('content')
    <div class="ibox box-primary">
        <div class="ibox-title">
            <div class="pull-right">
                <a href="{{url('admin/developer/setting/create')}}" class="btn btn-primary">
                    <i class="fa fa-plus"></i> اضافة اعداد جديد
                </a>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="ibox-content">

            @if(!empty($records) && count($records)>0)
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <th>#</th>
                        <th> القسم </th>
                        <th> (label) اسم  </th>
                        <th>(field) اسم</th>
                        <th>القيمة</th>
                        <th>validations</th>
                        <th>(field) نوع</th>
                        <th class="text-center">تعديل</th>
                        <th class="text-center">حذف</th>
                        </thead>
                        <tbody>
                        @php $count = 1; @endphp
                        @foreach($records as $setting)
                            <tr id="removable{{$setting->id}}">
                                <td>{{$setting->level}}</td>
                                <td>{{optional($setting->category)->name}}</td>
                                <td>{{optional($setting)->display_name}}</td>
                                <td>{{optional($setting)->key}}</td>
                                <td>{{optional($setting)->value}}</td>
                                <td>{{optional($setting->validation)->value}}</td>
                                <td>{{optional($setting)->data_type}}</td>
                                <td class="text-center"><a href="{{url('admin/developer/setting/' . $setting->id .'/edit')}}" class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a></td>
                                <td class="text-center">
                                    <button id="{{$setting->id}}" data-token="{{ csrf_token() }}" data-route="{{URL::route('setting.destroy',$setting->id)}}"  type="button" class="destroy btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                            @php $count ++; @endphp
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {!! $records->render() !!}
            @else
                <div>
                    <h3 class="text-info" style="text-align: center"> لا توجد بيانات للعرض </h3>
                </div>
            @endif


        </div>
    </div>
@stop

@section('script')
    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true,
            'showImageNumberLabel':false,

        })
    </script>
@stop